### PR TITLE
minor clean up

### PR DESCRIPTION
**Pull request by Smattr**
Let me know if you want me to change any of these commits or squash them into a single one. Thanks!

### CODE REVIEW

**Comment by cvengler** [comment]
Thank you for your commit, but I also cleaned up the codebase a few minutes ago and I have not seen that PR was opened, sorry my fault.
This means we have merging conflicts.
Can you do your commit on the current codebase again ?
Sorry for the extra work but otherwise I cannot merge it.
You might need to open another PR

Greetings, Emil

**Comment by Smattr** [comment]
No problem. Done. Note that I dropped some of the commits that are now irrelevant.

**Comment by cvengler** [comment]
LGTM
Thank you :-)

**Comment by cvengler** [comment]
Merged

**Comment by Smattr** [comment]
Thanks!

**Pull request merged**
