### PR TITLE
Support for pip (python)

### PR DESCRIPTION
**Pull request by ghost**
Everything should work, I tested it on lubuntu 18.10.
 I hope I did the pull request correctly

### CODE REVIEW

**Comment by ghost** [comment]
tfw default descriptions of GitHub, sorry for that
however it works

**Comment by cvengler** [comment]
Hello GodereskyIT,
thank you a lot for taking the time to contribute to sysget.
However there are still some issues in the code that you should fix before I can merge:

1. Why you have removed the build status in the README
2. Please use pip3 instead of pip due to the fact that python2 will be discontinued in 2020
3. Why you have appended pip in the middle of the vector package_manager_list ? Then the flatpak info notice wouldn't work anymore. Please append it to the end
4. You forgot to append pip in packjage_manager_list in utils.cpp

Greetings and good luck, Emil

**Comment by ghost** [comment]
Owh, sorry
Now everything should be correct, right?

**Comment by cvengler** [comment]
Sorry that it took me so long to answer :(
I will merge now :+1:

**Pull request merged**
